version: "2.1"
  services:
    database:
      image: postgres:10
      expose: 
        - "5432"
    django:
      image: django:test
      volumes:
        - host_dir:container_dir
      ports:
        - "8000:8000"