version: "2.1"

services:
  database:
    image: postgres:10
    expose:
      - "5432"
    restart: always
    environment:
      POSTGRES_PASSWORD: secret
  django:
    build: .
    ports:
      - "8000:8000"
    volumes:
      - ./messanger:/messanger
    command: python messanger/manage.py runserver 0.0.0.0:8000
    depends_on:
      - database
      - redis
      - celery
      - flower
      - beat
  events:
    image: centrifugo/centrifugo:latest
    expose:
      - "8001"
    ports:
      - "8001:8001"
    volumes:
      - ./centrifugo:/centrifugo
    ulimits:
      nofile:
        soft: 65536
        hard: 65536
    command: centrifugo -c centrifugo_config.json --admin --debug
    depends_on:
      - django
  celery:
    build: .
    volumes:
      - ./messanger:/messanger
    working_dir: /messanger
    command: celery -A application worker -l info
    depends_on:
      - database
      - redis
  beat:
    build: .
    volumes:
      - ./messanger:/messanger
    working_dir: /messanger
    command: celery -A application beat -l info
    depends_on:
      - database
      - redis
  flower:
    build: .
    volumes:
      - ./messanger:/messanger
    ports:
      - "5555:5555"
    working_dir: /messanger
    command: flower -A application
    depends_on:
      - database
      - redis
  redis:
    image: redis
    expose:
      - "6379"
    ports:
      - "6379:6379"
    volumes:
      - ./redis:/data/redis
    command: redis-server /data/redis/redis.conf
