version: "2.1"

services:
  database:
    image: postgres:10
    expose: 
      - "5432"
  django:
    build: .
    ports:
      - "8000:8000"
    volumes:
      - ./messanger:/messanger
    command: python messanger/manage.py runserver 0.0.0.0:8000
    depends_on:
      - database
  events:
    image: centrifugo/centrifugo:latest
    expose:
      - "8001"
    ports:
      - "8001:8001"
    depends_on:
      - django