version: "2.1"

services:
  database:
    image: postgres:10
    expose:
      - "5432"
    restart: always
    environment:
      POSTGRES_PASSWORD: secret
  django:
    build: .
    ports:
      - "8000:8000"
    volumes:
      - ./messanger:/messanger
    command: python messanger/manage.py runserver 0.0.0.0:8000
    depends_on:
      - database
  events:
    image: centrifugo/centrifugo:latest
    expose:
      - "8001"
    ports:
      - "8001:8001"
    volumes:
      - ./centrifugo:/centrifugo
    ulimits:
      nofile:
        soft: 65536
        hard: 65536
    command: centrifugo -c centrifugo_config.json --admin --debug
    depends_on:
      - django
